<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Inclusions</name>
   <tag></tag>
   <elementGuidId>c611c224-328a-42bd-bf2e-233ddf22a9a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='INCLUSIONS']//*[contains(@class,'col-md-12')]/div[${value}]//label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='INCLUSIONS']//*[contains(@class,'col-md-12')]/div[${value}]//label</value>
   </webElementProperties>
</WebElementEntity>
