<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Exclusions</name>
   <tag></tag>
   <elementGuidId>dc39666d-5af5-48b0-bae4-7efa82dbac11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='EXCLUSIONS']//*[contains(@class,'col-md-12')]//div[${value}]//label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='EXCLUSIONS']//*[contains(@class,'col-md-12')]//div[${value}]//label</value>
   </webElementProperties>
</WebElementEntity>
