<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TourStatus</name>
   <tag></tag>
   <elementGuidId>da061d32-b297-467e-aa7d-de8804d22aff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//select[@name='tourstatus']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
