<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Supplier</name>
   <tag></tag>
   <elementGuidId>d5059fbc-9aa5-45df-9407-6e592c0178fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>.//tbody//*[contains(text(),'saranya@demo.com')]//parent::*//preceding-sibling::*//child::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
